#!/bin/bash

# First: Update repositories:
sudo apt update && sudo apt upgrade -y && sudo apt dist-upgrade -y && sudo apt autoremove -y && sudo apt autoclean && sudo apt clean && sudo snap refresh
# now some personalization
# Install powerline-shell
sudo apt install python3-pip
pip install powerline-shell
# copy insult-libary to /etc
sudo cp etc/bash.command-not-found /etc
# append various aliases, powerline and insulter to .bashrc
cat append-to-your-bashrc >> ~/.bashrc
