#!/bin/bash
#
#######################################
#
# Example for downloading and installing a Package in .deb-format:
# --------------------------------------------------------------
# url=$(curl -s https://web.site/downloads | grep Ubuntu64 | cut -d\" -f2)
# wget "$url"
# dpkg -i "${url##*/}"
#
##############################################
# Get Visual Studio Code and install it
##############################################
sudo snap install --classic code
#
##############################################
# Get VMWare Workstation and install it
##############################################
#
cd ~/Downloads
wget --user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0" https://www.vmware.com/go/getworkstation-linux
chmod +x ~/Downloads/getworkstation-linux
sudo sh ~/Downloads/getworkstation-linux
#
# Fix for fucked up Workstation:
# Get hostmodules
wget https://github.com/mkubecek/vmware-host-modules/archive/workstation-16.2.3.tar.gz
# unpack file and enter subdir
tar -xzf workstation-16.2.3.tar.gz
cd vmware-host-modules-workstation-16.2.3/
# pack needed hostmodules
tar -cf vmmon.tar vmmon-only
tar -cf vmnet.tar vmnet-only
# copy hostmodules to vmwaredir and compile them into kernel
sudo cp -v vmmon.tar vmnet.tar /usr/lib/vmware/modules/source/
sudo vmware-modconfig --console --install-all
#
# now some personalization
# Install powerline-shell
sudo apt install python3-pip
pip install powerline-shell
# copy insult-libary to /etc
sudo cp etc/bash.command-not-found /etc
# append various aliases, powerline and insulter to .bashrc
cat append-to-your-bashrc >> ~.bashrc
