#!/bin/bash

# First: Update repositories:
sudo apt update && sudo apt upgrade -y && sudo apt dist-upgrade -y && sudo apt autoremove -y && sudo apt autoclean && sudo apt clean && sudo snap refresh
# now some personalization
#
# Install powerline-shell
sudo apt install python3-pip
pip install powerline-shell
sudo pip install powerline-shell
# copy insult-libary to /etc
sudo cp etc/bash.command-not-found /etc
# append various aliases, powerline and insulter to .bashrc and copy it also to /root
cat append-to-your-bashrc >> ~/.bashrc
cp ~/.bashrc /root/.bashrc
# enable F-Keys as primary-Keys on Apple-keyboard (Wired and Wireless BT TKL-Version)
echo options hid_apple fnmode=2 | sudo tee -a /etc/modprobe.d/hid_apple.conf
sudo update-initramfs -u -k all
